version: '2'
services:

  app:
    container_name: internship-loans-app
    image: internship-loans:1.0
    tty: true
    stdin_open: true
    command: sh ./docker/app-container-entrypoint.sh
    volumes:
      - .:/var/www
      - ./docker:/var/www/docker
      - ~/.ssh/id_rsa:/root/.ssh/id_rsa
      - ~/.ssh/id_rsa.pub:/root/.ssh/id_rsa.pub
    ports:
      - "3031:3000"
    depends_on:
      - db
    dns:
      - 8.8.8.8
      - 9.9.9.9

  db:
    container_name: internship-loans-db
    image: internship-loans-db:1.0
    volumes:
      - ./docker:/var/www/docker
      - ~/data/postgresql/internship_loans:/var/lib/postgresql/data
      - ~/.ssh/id_rsa:/root/.ssh/id_rsa
      - ~/.ssh/id_rsa.pub:/root/.ssh/id_rsa.pub
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: loans_development
    expose:
      - "5432"
    command: sh /var/www/docker/db-entrypoint.sh
